version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/ai-content-manager
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - PATREON_CLIENT_ID=${PATREON_CLIENT_ID}
      - PATREON_CLIENT_SECRET=${PATREON_CLIENT_SECRET}
      - PATREON_CREATOR_ACCESS_TOKEN=${PATREON_CREATOR_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BLOG_API_URL=${BLOG_API_URL}
      - BLOG_API_KEY=${BLOG_API_KEY}
    networks:
      - app-network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  # Frontend client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - app-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
